Refactor: Separate out prompt generation from model.
google/oss-fuzz-gen pull request #118
Opened 2024-02-21 05:17 UTC by oliverchang

The logic was getting a bit too entangled and difficult to extend.

This breaks out the prompt generation into its a separate prompt_builder module, as well as introduces Prompt classes (with both TextPrompt and OpenAIPrompt as two implementations).

This also changes the model interfaces to take in a Prompt object instead of `prompt_path`. `prompt_path` was only really needed for logging and AIBinaryModel.

Ref: #62.

2024-02-21 05:46 UTC, oliverchang commented
@mihaimaruseac @DonggeLiu would one of you be able to help test the OpenAI bits? I don't have access to test.

2024-02-21 16:06 UTC, mihaimaruseac commented
I'll run some tests for that today.

2024-02-22 01:39 UTC, DonggeLiu approved these changes
Thanks! Some nits for consistency.

2024-02-22 01:39 UTC, DonggeLiu commented on llm_toolkit/prompt_builder.py
> +    """Build a prompt."""
nit: Builds

2024-02-22 01:39 UTC, DonggeLiu commented on llm_toolkit/prompt_builder.py
> +    """Find template file based on |template_dir|."""
nit: Finds

2024-02-22 01:39 UTC, DonggeLiu commented on llm_toolkit/prompts.py
> +    """Save the prompt to a filelocation."""
nit: Saves

2024-02-22 01:39 UTC, DonggeLiu commented on llm_toolkit/prompts.py
> +    """Save the prompt to a filelocation."""
nit: Saves

2024-02-22 02:00 UTC, oliverchang commented
> Thanks! Some nits for consistency.

Thanks, fixed!

2024-02-22 02:01 UTC, DonggeLiu commented
@oliverchang Would you mind requesting an experiment once the docker image is updated?

2024-02-22 02:39 UTC, DonggeLiu commented
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1/llm-experiment/default/ofg-pr-118-dg
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-22-118-dg-comparison/index.html
BUCKET: https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-02-22-118-dg-comparison
BUCKET GS: `gs://oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-02-22-118-dg-comparison`

2024-02-22 05:27 UTC, oliverchang commented
OK! Just waiting on @mihaimaruseac to help test the OpenAI bits to make sure I didn't break anythign there :)

2024-02-22 19:32 UTC, mihaimaruseac requested changes
So, this works for OpenAI for generating the initial code but it has an issue when generating fixes

```
Debug key='content' value=[{'role': 'system', 'content': 'Given the following C++ program and its build error message, fix the code to achieve the original functionality.\n\nIf
 a function is missing, fix it by including the related libraries.\n\nIf the error contains "undefined reference to", this means one or more of the header <code>#include</code>
 directives need to be wrapped with <code>extern "C" {}</code> for the object linking to succeed. You must fix this by rewriting the relevant <code>#include</code> and wrapping
 it with <code>extern "C" {}</code>.\n'}] 
```

Instead of the JSON array there, that should be a string. I think I have a fix, will try it and add a suggested edit

2024-02-22 20:32 UTC, merged

2024-02-22 23:47 UTC, oliverchang commented on llm_toolkit/prompts.py
> +class OpenAIPrompt(Prompt):
Hmm, how standardised is this structure? My thinking was it was very OpenAI specific as opposed to be a more generalised prompt format.