Simplify the nested condition of textcov
google/oss-fuzz-gen pull request #496
Opened 2024-07-17 16:59 UTC by arthurscchan

The conditional check of array_count larger than 0 is not necessary since it is only used in repeating '[]' in the next_arg and the repeat of string won't happen if the array_count is less than or equals 0. This PR removes the unnecessary conditional check to simplify the logic and decrease the amount of nested conditional checking.

2024-07-18 03:28 UTC, oliverchang approved these changes

2024-07-18 10:36 UTC, DavidKorczynski commented
/gcbrun skip

2024-07-18 10:43 UTC, DavidKorczynski requested changes

2024-07-18 10:43 UTC, DavidKorczynski commented on experiment/textcov.py
> +            next_arg = f'{next_arg}{"[]" * array_count}'
Could we change this to `next_arg += f'{"[]" * array_count}'` -- isn't it a bit easier to read?

2024-07-19 14:31 UTC, DavidKorczynski approved these changes

2024-07-19 14:35 UTC, merged